{{- $fullname := include "sumoffice.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-jwt
  labels:
    {{- include "sumoffice.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ required "jwtSecret is required" .Values.jwtSecret | quote }}
